In [53]:
from sdRDM import DataModel
import matplotlib.pyplot as plt
import numpy as np

%reload_ext autoreload
%autoreload 2
from EnzymePynetics.core import EnzymeKinetics
from EnzymePynetics.tools import ParameterEstimator

In [54]:
enzymekinetics, _ = DataModel.parse(
    path="/Users/max/code/EnzymePynetics/irrev_MM_enzyme.json"
)

enzymekinetics

EnzymeKinetics(id='enzymekinetics3', title='test irreversible MM', kinetic_models=[], measurements=[Measurement(id='measurement18', species=[Species(id='species25', name=None, conc_unit='mmol / l', initial_conc=0.5, species_type='substrate', data=[Series(id='series24', values=[0.5, 0.3644854817261172, 0.26342082614495876, 0.18911029730907936, 0.13507619854228237, 0.09611819057303306, 0.06820762065153442, 0.04830485333484994, 0.034160437082733246, 0.024132875363550937, 0.017036342307101854, 0.012020366602019189, 0.008478109651294722, 0.005978153688854039, 0.004214590282762656, 0.002970893213232844, 0.0020940108248797087, 0.0014758522649185415, 0.0010401279274423667, 0.0007330218757907535, 0.0005165793991943711])]), Species(id='species26', name=None, conc_unit='mmol / l', initial_conc=0.01, species_type='enzyme', data=[])], enzyme_conc=None, temperature=37.0, temperature_unit='C', pH=7.0, time=[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17

In [55]:
pe = ParameterEstimator(enzymekinetics)
print(pe.inhibitor)
pe.fit_models()

# order of y0s does not match order in implemented kinetic models

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Fitting data to:
 - irreversible Michaelis Menten model
 - competitive product inhibition model
 - uncompetitive product inhibition model
 - non-competitive product inhibition model
 - substrate inhibition model


AIC       kcat [1/min]    Km [mmol / l]  \
irreversible Michaelis Menten      -5478  140.000 +/- 0.00%  4.000 +/- 0.00%   
competitive product inhibition     -1384  140.129 +/- 0.02%  3.983 +/- 0.07%   
uncompetitive product inhibition   -1130  141.259 +/- 0.05%  4.055 +/- 0.19%   
substrate inhibition               -1130  143.767 +/- 0.06%  4.222 +/- 0.20%   
non-competitive product inhibition -1057  141.386 +/- 0.13%  4.038 +/- 0.45%   

                                   kcat / Km [1/min * 1/mmol / l]  \
irreversible Michaelis Menten                    35.000 +/- 0.00%   
competitive product inhibition                   35.179 +/- 0.07%   
uncompetitive product inhibition                 34.837 +/- 0.19%   
substrate inhibition                             34.052 +/- 0.21%   
non-competitive product inhibition               35.017 +/- 0.47%   

                                   Ki competitive [<bound method ParameterEstimator._subset_data of <EnzymePynetics.tools.parameterestimator.ParameterEstimator object at 0x288b573a0>>]  \
irreversible Michaelis Menten                                                       -                                                                                                      
competitive product inhibition                                     1000.000 +/- 0.01%                                                                                                      
uncompetitive product inhibition                                                    -                                                                                                      
substrate inhibition                                                                -                                                                                                      
non-competitive product inhibition                                1000.000 +/- 30.44%                                                                                                      

                                   Ki uncompetitive [<bound method ParameterEstimator._subset_data of <EnzymePynetics.tools.parameterestimator.ParameterEstimator object at 0x288b573a0>>]  
irreversible Michaelis Menten                                                       -                                                                                                       
competitive product inhibition                                                      -                                                                                                       
uncompetitive product inhibition                                   1000.000 +/- 0.13%                                                                                                       
substrate inhibition                                                999.999 +/- 1.12%                                                                                                       
non-competitive product inhibition                                1000.000 +/- 14.06%

In [56]:
y0s = pe._get_y0s(
    substrate=pe.substrate, enzyme=pe.enzyme, product=pe.product, inhibitor=pe.inhibitor
)

## Test KineticModel

In [62]:
model = pe.models["irreversible Michaelis Menten"]

res = model.fit(pe.substrate, pe.time, y0s)

model.result

ModelResult(id='modelresult5', name='irreversible Michaelis Menten', equation='#TODO', parameters=[Parameter(id='parameter6', name='k_cat', value=139.99999997847823, standard_deviation=1.941721384697543e-09, correlations=[Correlation(id='correlation6', parameter='Km', value=0.9142541220927958)], upper_limit=12322.327495186193, lower_limit=1.2322327495186194), Parameter(id='parameter7', name='Km', value=3.9999999977466065, standard_deviation=2.3610069690129153e-10, correlations=[Correlation(id='correlation7', parameter='k_cat', value=0.9142541220927958)], upper_limit=6161.163747593097, lower_limit=0.006161163747593097)], AIC=-5478.488289715518, BIC=-5472.815725901614, RMSD=3.5606567862629054e-10)

In [ ]:
res